[project]
name = "browser-use"
description = "Make websites accessible for AI agents"
authors = [
    { name = "Gregor Zunic" }
]
<<<<<<< HEAD
version = "0.1.36"
readme = "README.md"
requires-python = ">=3.11,<4.0"
=======
version = "0.1.17"
readme = "README.md"
requires-python = ">=3.11"
>>>>>>> 39aa9e72dfecf6c485004f90b2b40190e4b0f1e3
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "MainContentExtractor>=0.0.4",
    "beautifulsoup4>=4.12.3",
<<<<<<< HEAD
    "httpx>=0.27.2",
    "langchain==0.3.14",
    "langchain-openai==0.3.1",
    "langchain-anthropic==0.3.3",
    "langchain-ollama==0.2.2",
    "langchain-fireworks>=0.2.6",
    "langchain-aws>=0.2.11",
    "langchain-google-genai==2.0.8",
    "pydantic>=2.10.4",
    "python-dotenv>=1.0.1",
    "requests>=2.32.3",
    "posthog>=3.7.0",
    "playwright>=1.49.0",
    "setuptools>=75.8.0",
    "lmnr[langchain]>=0.4.59",
    "markdownify==0.14.1"
=======
    "httpx==0.27.2",
    "langchain>=0.3.9",
    "langchain-openai>=0.2.10",
    "langchain-anthropic>=0.3.0",
    "langchain-fireworks>=0.2.5",
    "pydantic>=2.10.2",
    "python-dotenv>=1.0.1",
    "requests>=2.32.3",
    "posthog>=3.7.4",
    "playwright>=1.49.0"
>>>>>>> 39aa9e72dfecf6c485004f90b2b40190e4b0f1e3
]

[project.optional-dependencies]
dev = [
    "tokencost>=0.1.16",
    "hatch>=1.13.0",
    "build>=1.2.2",
    "pytest>=8.3.3",
    "pytest-asyncio>=0.24.0"
]

[tool.ruff]
<<<<<<< HEAD
line-length = 130
select = ["E", "F", "I"]
fix = true
=======
line-length = 100
>>>>>>> 39aa9e72dfecf6c485004f90b2b40190e4b0f1e3

[tool.ruff.format]
quote-style = "single"
indent-style = "tab"
docstring-code-format = true

[build-system]
requires = ["hatchling"]
<<<<<<< HEAD
build-backend = "hatchling.build"
=======
build-backend = "hatchling.build"
>>>>>>> 39aa9e72dfecf6c485004f90b2b40190e4b0f1e3
